[[coordgenlibs]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5454fabb86f690876408f178ff098f3325361d49"
libc = "musl"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "a9aedde8d18f455c71e31ad6095fb97ed34186d61ada33f2191dd9377692038e"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v1.4.0+0/coordgenlibs.v1.4.0.aarch64-linux-musl-cxx03.tar.gz"
[[coordgenlibs]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f7d0a4b44c3560962a1ceebef1d136d2eae07cb8"
libc = "musl"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "a8fecb8f0039c4f1e1a82892c25c4c4b0fd5d419d3b0755789bd8f237db6743c"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v1.4.0+0/coordgenlibs.v1.4.0.aarch64-linux-musl-cxx11.tar.gz"
[[coordgenlibs]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fceb373a493579201dadebfeb87ffb1c795398a3"
libc = "musl"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "be1bb909704b09fdeed771460c6a396323eab1bb75071e37aed0dc1a3bc073eb"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v1.4.0+0/coordgenlibs.v1.4.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[coordgenlibs]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fb0090b22e13a7959b29129a6b9ed4f7ed2e11a5"
os = "windows"

    [[coordgenlibs.download]]
    sha256 = "19e8ea811fa781f1893f9d3a4921aa3802dab5720f98c1709458d9a1dca2074a"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v1.4.0+0/coordgenlibs.v1.4.0.x86_64-w64-mingw32-cxx11.tar.gz"
[[coordgenlibs]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bcda7126ba42934d86953e5fb437bc8645afacd5"
libc = "musl"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "f851b1726b1bd2fdb55163c83869665be1898a1255f0ae4ac467d119af5a99a2"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v1.4.0+0/coordgenlibs.v1.4.0.i686-linux-musl-cxx11.tar.gz"
[[coordgenlibs]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "58a9f532414c34d20d42014eafb7812990203f5d"
libc = "musl"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "71fa05bc510d485211aba9ffcaf614504dca4412ab57bb1d3684bf36cae36c15"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v1.4.0+0/coordgenlibs.v1.4.0.x86_64-linux-musl-cxx11.tar.gz"
[[coordgenlibs]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4e63a9239ee2f1b65427ac71597fac519fcc39d3"
libc = "glibc"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "3ce4cf831a7f829f0f7d581f7cb4c77adadf41e6b4a2c08f7a850aed3a03af1e"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v1.4.0+0/coordgenlibs.v1.4.0.x86_64-linux-gnu-cxx03.tar.gz"
[[coordgenlibs]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "94ff360bf5776c39d65325c6fef1ba47096c3788"
libc = "glibc"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "09ac3c57b33c85fd7e533f554074104c0ae07725858b5f9dcfa910f2d1841db7"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v1.4.0+0/coordgenlibs.v1.4.0.i686-linux-gnu-cxx03.tar.gz"
[[coordgenlibs]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f6517f8c9d9f7d5e58f717926a54735c240d58f1"
os = "macos"

    [[coordgenlibs.download]]
    sha256 = "c7425983aa63385815ef8d80400d60819683c44e9a3f69861e33328b63085921"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v1.4.0+0/coordgenlibs.v1.4.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[coordgenlibs]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "383e7a5ed1d341efaf1ad0ceaaf5f1f9f75e970d"
libc = "glibc"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "e868a6027a3475b527a4fa845bcc36506db34e341265aa6e1b7361202fde6b33"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v1.4.0+0/coordgenlibs.v1.4.0.i686-linux-gnu-cxx11.tar.gz"
[[coordgenlibs]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "80670820f31445b8164165fb47ec630ed713998f"
os = "windows"

    [[coordgenlibs.download]]
    sha256 = "cb9663001bed9c8c242c44ea6449ea8039c484dba2d6675e2dfa353304d5e58c"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v1.4.0+0/coordgenlibs.v1.4.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[coordgenlibs]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8997098867b79b32dea59dd0647d757f0750bab9"
libc = "glibc"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "1e5907adb7df194d3a5abd08aae74dbd11a5afa7eba22ac351ccd4d170443797"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v1.4.0+0/coordgenlibs.v1.4.0.x86_64-linux-gnu-cxx11.tar.gz"
[[coordgenlibs]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f1af6266272c86577e8a69b3ccbd15b2133bc62"
libc = "glibc"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "0ac3f9fb4caba3360435cdc43ea1cc58a6c3604dc23f7bd2de27ff4a9e9e8e4b"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v1.4.0+0/coordgenlibs.v1.4.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[coordgenlibs]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0d66baff2f9e264dcb5a41ae20c1997432900ecf"
libc = "glibc"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "81347a8cde0ee10bd29cea175c435c413afd66730e25ceb14b69b90012c93490"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v1.4.0+0/coordgenlibs.v1.4.0.aarch64-linux-gnu-cxx11.tar.gz"
[[coordgenlibs]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "65d4ad55c228bc99a7b69cb7e5665584db061f40"
libc = "musl"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "8a52a8f8fff7b9582e59b309f171fefe5621e116e437fd2a3c2ade1f453912e4"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v1.4.0+0/coordgenlibs.v1.4.0.x86_64-linux-musl-cxx03.tar.gz"
[[coordgenlibs]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "066cc1b9ec9a4c2fa43372f19a0891ec523535a2"
os = "macos"

    [[coordgenlibs.download]]
    sha256 = "d08513fb5c26ca69e59fddbf2d97816e6c2e5ddfd2d93942d411d2802a4471a7"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v1.4.0+0/coordgenlibs.v1.4.0.x86_64-apple-darwin14-cxx03.tar.gz"
[[coordgenlibs]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9d554e1ff548c46db687c69eae168c3a10716aef"
os = "freebsd"

    [[coordgenlibs.download]]
    sha256 = "b8840503c748dfc111a0b48f84cf4c4090fd718f07e709dca56925a1fb7a05d3"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v1.4.0+0/coordgenlibs.v1.4.0.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[coordgenlibs]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fcd6d5947c9e822fa1eeb0abe8855976ceb2fa3e"
libc = "glibc"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "d6d2d7e4c1be669d93b546c9fa14b07b00ac8260f01487f95e8e575e68a83591"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v1.4.0+0/coordgenlibs.v1.4.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[coordgenlibs]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "72ce364f234aed839cc38f4d6378a8adb3ddcec6"
os = "windows"

    [[coordgenlibs.download]]
    sha256 = "f536a766cf368cd32a22d70e700b3e011c929c21f3938651a3f3ccd551bd0c85"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v1.4.0+0/coordgenlibs.v1.4.0.i686-w64-mingw32-cxx03.tar.gz"
[[coordgenlibs]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5bbf1a196ecfd52a7c981e255abaa4b1c2a75432"
os = "windows"

    [[coordgenlibs.download]]
    sha256 = "b45d4871cbb77b95ca96da6aaa2eee262535bcbcdb526fa34d62e3e1335d326a"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v1.4.0+0/coordgenlibs.v1.4.0.i686-w64-mingw32-cxx11.tar.gz"
[[coordgenlibs]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "97c6a469e3cd8ad0743c9523dc547e286728dda1"
libc = "musl"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "39dbdca0e45b0f4652c46fde49b648688b5744b226fad49aca07911a7c1f3bf9"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v1.4.0+0/coordgenlibs.v1.4.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[coordgenlibs]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ddafc417458493bd7e3d829594e8ced48293563c"
libc = "glibc"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "d2564d45fb0004ac901288db5194a0770ea63eb848910169f485c6bd4d82a697"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v1.4.0+0/coordgenlibs.v1.4.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[coordgenlibs]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d2036b1c2b8fc8e407a5cb96c461413f03fe1267"
libc = "glibc"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "5d2f846c185fc4758ffd57f4a7105c1e303cb89297e94bee710e1dbb6c59eedb"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v1.4.0+0/coordgenlibs.v1.4.0.aarch64-linux-gnu-cxx03.tar.gz"
[[coordgenlibs]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a0298d0cbe6825821fc9b0df58c233dd4f7ab5e"
libc = "glibc"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "14a1ea09602cb32314b9669d08d849e0fdec791cd6e8095da8ba055cd356c345"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v1.4.0+0/coordgenlibs.v1.4.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[coordgenlibs]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d7ab2dcdc282f831c9f056e78b7269bf209a713c"
os = "freebsd"

    [[coordgenlibs.download]]
    sha256 = "2048656da89958cb0d56ccc4bffa0c04b3cdc0dbc4cb264c27ec387c773eca99"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v1.4.0+0/coordgenlibs.v1.4.0.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[coordgenlibs]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7b064d6151e07d9f5f9d64363f799bd29c84dbb9"
libc = "musl"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "a4b89cf283b5b7725d704bf039b3484dbc8dd7e77f8a783b0e7516916d60308f"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v1.4.0+0/coordgenlibs.v1.4.0.i686-linux-musl-cxx03.tar.gz"
