[[coordgenlibs]]
arch = "aarch64"
git-tree-sha1 = "46bfc8e12c885bbf8e8f6aaf87d1920681209b1a"
os = "macos"

    [[coordgenlibs.download]]
    sha256 = "b276e6e496f54ab48a685dee39eafc9d6d9da353b55b9819447347f414bf898d"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v3.0.1+0/coordgenlibs.v3.0.1.aarch64-apple-darwin.tar.gz"
[[coordgenlibs]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "18d859eb2349c8873979e8ba2b2e6deb9476261e"
libc = "glibc"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "5a0a711d7b8814b9e26491b327056ace2dc561bcf50d852b894a95b7355938ab"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v3.0.1+0/coordgenlibs.v3.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[coordgenlibs]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8aa895ee3b928b03bd28ad8875062c4c73bde68e"
libc = "glibc"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "7f821e416cd8f40fb7791488b63a3dc138905ec56b0b36081f7b17e4deba07db"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v3.0.1+0/coordgenlibs.v3.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[coordgenlibs]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e06a82560bdba4eed8aca2e1dd3a18ccb5b4052d"
libc = "musl"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "c2436940f9ce4a87e3514c2a3c34c554f5bf85b461e19b5ed996b442fc77ff91"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v3.0.1+0/coordgenlibs.v3.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[coordgenlibs]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7fc89387afb3661733547a1bc761e5f7c63307cf"
libc = "musl"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "deac0c4ab862ea7c41166bbb66cb0958f3d2e942a7e98f4acd2983fdb68449b6"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v3.0.1+0/coordgenlibs.v3.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[coordgenlibs]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1e9677a0b8a7554977eb381293cfb08de9441add"
libc = "glibc"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "87804aff9e3b7ea7540c4cf146be4520cf6070c2edeb524073ecce92e06ca3df"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v3.0.1+0/coordgenlibs.v3.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[coordgenlibs]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dc258d36d278a061bd01c038e176c16a04485221"
libc = "glibc"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "fecac783586f9a0e292ece88634faf06e8b81b56dbdb096715d21c3a0cc70829"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v3.0.1+0/coordgenlibs.v3.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[coordgenlibs]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "97d4ac5533b001913720ece2d6da230db202ad01"
libc = "musl"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "cdc5edbbd2c9a89a2c74443af94c9a52d3c8a6e8f76bf5deaf6b81750f9f345b"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v3.0.1+0/coordgenlibs.v3.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[coordgenlibs]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bcd5c9efacbfe45e4daed08ce83af0504c690c3b"
libc = "musl"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "593e296c0d1bbcc90f25bc6066d53428704f48fa40d0a0e1b91533869f51e535"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v3.0.1+0/coordgenlibs.v3.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[coordgenlibs]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c392674230176d3404dd853794cee6e1d788fa40"
libc = "glibc"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "5d5aa915d7c10416e3799572b35c7c81cf11d55defec39504bca816e5e00f7dc"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v3.0.1+0/coordgenlibs.v3.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[coordgenlibs]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8791b7a3487d14dc8bebb5f8c3d46b260bbd578f"
libc = "glibc"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "bcf4b100cf2d8cfc69fd58bcdf3e3d10d30778c0dd43a1459eab65657f239d8b"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v3.0.1+0/coordgenlibs.v3.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[coordgenlibs]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "394152a9fb6b6bc107ead75238d8200c5f642a89"
libc = "musl"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "6798d054d80b9051a117a2cee4f34e702b8064cbd6e634d52124c4c1ec843f45"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v3.0.1+0/coordgenlibs.v3.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[coordgenlibs]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "24c84e79cdd88c6a173a97f6318e2913cb7fab23"
libc = "musl"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "581354287f6a303eb129739a8e994097ea2c5c0afce5bfabc65421e00e8dd148"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v3.0.1+0/coordgenlibs.v3.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[coordgenlibs]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b62ac47956d01797c860f8ee88daec3a1134c0ef"
libc = "glibc"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "0637eed48f93255659264df4a74460866d6db7576f646f1ba800ee63eb3c09fb"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v3.0.1+0/coordgenlibs.v3.0.1.i686-linux-gnu-cxx03.tar.gz"
[[coordgenlibs]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9eaf22f9cf6ca2446285c0b548fa24ad41711d3a"
libc = "glibc"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "aedd3ee573cabf9d7dd64bc0efa2827ff050db562546ffba2088cebee5032bcb"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v3.0.1+0/coordgenlibs.v3.0.1.i686-linux-gnu-cxx11.tar.gz"
[[coordgenlibs]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9125565a0125eecb431f09e1896c89c64028ccd5"
libc = "musl"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "dcd930164488aa7406be89cfd981b3553ddb7d558568599dc2057e74a426fd26"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v3.0.1+0/coordgenlibs.v3.0.1.i686-linux-musl-cxx03.tar.gz"
[[coordgenlibs]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aaa35a79d2a11445568c1ec03ae1cb2a5e3691d7"
libc = "musl"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "eb45b8c0a222ed9e16187c71717dd7d8a4876b5d9ed82015f5c103f7f3938c03"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v3.0.1+0/coordgenlibs.v3.0.1.i686-linux-musl-cxx11.tar.gz"
[[coordgenlibs]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c21409dade58c9278126594bab81528fc6edcf8b"
os = "windows"

    [[coordgenlibs.download]]
    sha256 = "00fd3fbe343e2147866955ed389f18543de5040518b193ad797df38c8b8cff7b"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v3.0.1+0/coordgenlibs.v3.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[coordgenlibs]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2348ca600e5b798c64d508bdca86aa841273a76a"
os = "windows"

    [[coordgenlibs.download]]
    sha256 = "b84a9bf8250afb0e6d960771366043919301bad2e457566a8aed0332d8a149ed"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v3.0.1+0/coordgenlibs.v3.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[coordgenlibs]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "00ff96d53b5d5ef36fb34ab3ba36cc0da7fba0b3"
libc = "glibc"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "72e9cfd22abaddb1ec9921727cd6b0bfa3e48278e86d597b82075cc1ccf072c2"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v3.0.1+0/coordgenlibs.v3.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[coordgenlibs]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7432468159e307d4b479ba5b2f5236549f04b76e"
libc = "glibc"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "47d57866b583c095b8dd6095641afa929d1854af2b75f40bf9d77ce6350aec95"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v3.0.1+0/coordgenlibs.v3.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[coordgenlibs]]
arch = "x86_64"
git-tree-sha1 = "6ca5867c77585dfd902eb9b48fb22e19ebdbca43"
os = "macos"

    [[coordgenlibs.download]]
    sha256 = "c503ff47fe17da0d6e5246a4dc71751925e54c11ef1a6b6a05b2840305823184"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v3.0.1+0/coordgenlibs.v3.0.1.x86_64-apple-darwin.tar.gz"
[[coordgenlibs]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "83666b6c3927b0a6c61f330a0b181c5873e83935"
libc = "glibc"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "c945d6d9f30e652b3b444a114c170848a78aaee9c1e6d2ad5114b39275f667b4"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v3.0.1+0/coordgenlibs.v3.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[coordgenlibs]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "56613964f0ccae5e281940a67473089e8a73eb0a"
libc = "glibc"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "a94f3118e66a15f7112d3c96890e660017364bd1a3aade04b1ab0c9a08490a69"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v3.0.1+0/coordgenlibs.v3.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[coordgenlibs]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aa541e1ed36af8c4f6b836642b118909f86331d4"
libc = "musl"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "711bf9cb35cf5606a91a1592c0aa9443c817f0734fbfb060114bd162f8e79b0a"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v3.0.1+0/coordgenlibs.v3.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[coordgenlibs]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "19074220500a4648903c6a9c4cf6a0bed32ca9d1"
libc = "musl"
os = "linux"

    [[coordgenlibs.download]]
    sha256 = "1f5117eee95e9f6cc01991b868ad5fd418f7c92e96f983387c703aa9dc2112fc"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v3.0.1+0/coordgenlibs.v3.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[coordgenlibs]]
arch = "x86_64"
git-tree-sha1 = "bf3a79100debb3a6e9a3ca106414732189ca3165"
os = "freebsd"

    [[coordgenlibs.download]]
    sha256 = "0b4e3b69e96cf6c1b54abfd022ead257b78adcb2907dbf934a70bf32e3c88bd6"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v3.0.1+0/coordgenlibs.v3.0.1.x86_64-unknown-freebsd.tar.gz"
[[coordgenlibs]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cec4a0584a3c0fdde3c3d2c673fa339908528199"
os = "windows"

    [[coordgenlibs.download]]
    sha256 = "6d30851aa3c096344275af2385729f08a87aff82e9729c7b5511d71d679d220b"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v3.0.1+0/coordgenlibs.v3.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[coordgenlibs]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "407b02a8a9f3b43a06751c26251f3186eac140fa"
os = "windows"

    [[coordgenlibs.download]]
    sha256 = "596a5030e2a97870dfe07cf79b7da09fb785ee99bbd7d1c9aa3aa2de70d0c29a"
    url = "https://github.com/JuliaBinaryWrappers/coordgenlibs_jll.jl/releases/download/coordgenlibs-v3.0.1+0/coordgenlibs.v3.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
