# Autogenerated wrapper script for coordgenlibs_jll for i686-w64-mingw32-cxx11
export libcoordgen

JLLWrappers.@generate_wrapper_header("coordgenlibs")
JLLWrappers.@declare_library_product(libcoordgen, "libcoordgen.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libcoordgen,
        "bin\\libcoordgen.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
